### ISSUE TITLE
Not working, possibly because of multi arch readline libs

### ISSUE THREAD

**Issue by infokiller** [ardagnir/athame#29]
I installed athame and tested it using ipython but it doesn't seem to work. I used `pmap` to verify that the ipython process indeed uses the system readline libs. I think the problem might be that I see two distinct readline libraries and one more symbolic links:
* `/usr/lib/libreadline.so*`
* `/lib/x86_64-linux-gnu/libreadline.so.*`
* `/usr/lib/x86_64-linux-gnu/libreadline.so` -> `/lib/x86_64-linux-gnu/libreadline.so.6`

Following the installation script, it seems that only the first one was patched (by the modification time of the file).

What's the best way to solve this?

Thanks!

**Comment by infokiller** [comment]
I was able to force it to use the patched readline version by running:
```shell
LD_LIBRARY_PATH=/usr/lib ipython
```

However, I got the following error:
```
Athame Failure: No athamerc found.
```

I checked and noticed that `/etc/athamerc` didn't have global read permissions. I added them and now I'm getting the following error:
```
Athame Failure: Vimbed failure.
```

**Comment by ardagnir** [comment]
I'll look into this when I get a chance but I think this might be fixed in
the newest unstable branch of athame (0.whatever) if you run setup with the
correct --libdir. I've done a lot of work on compatibility that hasn't made
it into master yet.

Alternately, with master and your path flag tweak, you can try looking in
your libraries for vimbed and put it in the other one. (Move it from
multiarch to /usr/lib or vice versa)

**Comment by infokiller** [comment]
Thanks @ardagnir for the quick response!
I'll try the newest unstable branch.

I don't understand your alternative suggestion- what do you mean by looking in my libraries for vimbed?

**Comment by ardagnir** [comment]
Vimbed is at $libdir/athame_readline. You might need to move it to the multiarch lib.

**Comment by infokiller** [comment]
This issue was solved once installed vimbed (using my plugin manager).
Any idea why that solved it? Shouldn't that be done in the installation script?

**Comment by ardagnir** [comment]
Vimbed is installed in a lib dir so that it is only loaded by programs that need it at whatever versions they need. Athame is probably telling vim the wrong location for the lib because you changed the env variable, but since you installed a copy of vimbed with your plugin manager, vim is just using that one.

**Comment by ardagnir** [comment]
The libdir flag should support this now without extra hackery
