### ISSUE TITLE
zsh plugins do not refresh while typing

### ISSUE THREAD

**Issue by klaxalk** [ardagnir/athame#57]
While typing, the plugins such as _zsh-autosuggestions_ and _zsh-syntax-highlighting_ do not get the memo that the line has changed. However, their hooks apply just fine when autocompleting with "tab," so I suppose it should be possible. 

I look into athame for a place where to possibly fix it. However, it is currently beyond my knowledge. If you could point me in the right direction, I will attempt to fix it.

**Comment by ardagnir** [comment]
This is because Athame only releases control to the main zsh loop for special chars like tab.

The best way to solve this is probably to find what Zsh function updates plugins on changes and call that for vim changes in Athame. The most difficult part is likely just figuring out what Zsh function does this.

**Comment by klaxalk** [comment]
Thanks, I understand. I will try to solve this.
