### ISSUE TITLE
Better neovim embedding

### ISSUE THREAD

**Issue by rgreenblatt** [ardagnir/athame#70]
First of all, this is an awesome project :).

When spawning terminals within neovim, it should (at least in theory) be possible for athame to use that neovim process. This would be useful for shared registers and a few other things. I am potentially interested in implementing this feature, but I don't have a great idea of how doable this is. As far as I can tell, this could be done by adding another option to start_vim which sources vimbed and ~/.athemrc in the existing instance and opens the appropriate file. athemrc would also need to be changed such that the bindings are buffer specific. Thought?

**Comment by ardagnir** [comment]
Thanks!

I agree that this would be useful, but the problem is that Athame expects a
normal vim buffer, so neovim would have to act like the current buffer is a
normal vim buffer, but display it as if it were a terminal buffer. The
other problem is we want neovim to send user keys to the shell which would
send keys to athame, which would send the keys to neovim. If you used the
same neovim, you'd get a loop unless it could tell which keys came directly
from the user and which came from athame.

**Comment by rgreenblatt** [comment]
Ah, I see.

Thanks for the help.
